### ISSUE TITLE
unauthorized issue.

### ISSUE THREAD

**Issue by Kros21** [zabo-api/zabo-sdk-js#19]
## What SDK version are you using?
"zabo-sdk-js": "^0.6.2"
### What technology and versions are you using that is causing issues with the SDK?
Unauthorized error.
Reactjs, node back-end.
### What did you do?
I have connected to zabo service using zabo.init(), connect(), onConnection()...
And I added new account using metamask,
but, I can see unauthorized error in backend(node js) now.

### What did you expect to see?
I guess it depends on any exception in sdk authorization logic.
For instance, such as old credential..

### What did you see instead?
I tried as other account or pc.
but I am getting the same error..

**Comment by Hackdom** [comment]
Hey @Kros21, what function call in nodejs is giving you an unauthorized error?

**Comment by Hackdom** [comment]
From further discussion in Discord, it seems that zabo.users.addAccount needed to be called in order to be authorized to the account information.
