### ISSUE TITLE
SDK checks both `isNode` and `isBrowser` in a single instantiation

### ISSUE THREAD

**Issue by el-mapache** [zabo-api/zabo-sdk-js#55]
Just wanted to say first off that this SDK has been great thus far, it was really straightforward to implement!

## What SDK version are you using?
1.0.2

### What technology and versions are you using that is causing issues with the SDK?

Express application, `node v12.16.0`, `express v4.16.4`

### What did you do?

* Instantiated an instance of the api client using our api key and secret:
```
await Zabo.init({{
      apiKey: PUBLIC,
      secretKey: SECRET,
      env: 'sandbox',
});
```

I then ran a spec (via `jest`) that called the client instantiation. I did this to inspect the shape of the client interface — I needed to determine what properties were necessary to define in our `.ts` files. Ordinarily I would mock this object out in specs, but I wanted an initial look at the instantiated client.

### What did you expect to see?

A successful connection by the client

### What did you see instead?

An error telling me to add a valid `clientId` to the initialize options.

This error is thrown because the code at `src/sdk`, on line 38, is checking if the current env is node. The same file then checks on line 66 to see if the current env is the browser.

Although the specific instance in which I encountered this error is definitely an edge case, I think this check should _probably_ be an `if / else`; we can safely assume we are not operating in the browser if the `isNode` check evaluates as `true`.

The main caveat to making this change would probably be if a user is executing the library in a node env, but wants to simulate a browser? For example, I'm unsure if a headless browser env running on e.g. `puppeteer` will have both `global` and `window` defined.

Either way, wanted to flag this in case others have experienced it. Thanks!

**Comment by dreinke** [comment]
Hey @el-mapache! Thanks for the feedback and also for highlighting this issue.
You are right about the `isBrowser` being an unnecessary conditional in this case and we can for sure improve that.
We are about to release a new patch version (v1.0.3) including this change.
