### ISSUE TITLE
Documentation questions

### ISSUE THREAD

**Issue by ryancwalsh** [zabo-api/zabo-sdk-js#68]
Hi friends at Zabo,

Thank you so much for the Zabo API! I'm very excited about it. :-)

I'm not experiencing an error or a problem, really. I'm just confused about the documentation and so am hoping for some clarification.

I have a server-side Zabo app (`"zabo-sdk-js": "^1.1.0"`) using Node.

I've read https://zabo.com/docs/#pagination and https://zabo.com/docs/#get-transaction-history, which has said for a while:

 > "We are working on a fully-featured WebSocket implementation of this call for our next release which will provide a much-improved experience."

Do you know when that will be available?

I'm also wondering if you could please clarify this section:

> This function returns a transaction history list for the current account. Many accounts have large transaction histories and require a lengthy period of time to retrieve a full dataset. This means that most accounts will not return any transactions on the first call, but will return an empty array with a `delay` value and `last_updated_at` will be `0`. The delay is an estimated number of seconds before the transaction history will be available, or, if there are transactions, the number of seconds it will take for the transaction history to update. The estimate is our best guess based on known factors, however the time could take much longer if the account has more transactions than anticipated. Make sure you are considering this delay before calling the transaction history again both via SDK or HTTP request. When making subsequent calls, the `last_updated_at` field will let you know if the full history has been retrieved. You may start seeing transactions in the list, however, if `last_updated_at` is still `0`, then we are still retrieving the history. When `last_updated_at` updates to a particularly useful timestamp, that will be the latest time at which a full history was accounted for. All transactions will be included if no currency is specified.

It wasn't obvious that "Optional ID of the resource to start from" meant the transaction ID, but that seems to be the case.

In my attempts to fetch *all* transactions for a given account ID, it's still not clear to me how to do it.  (If you could provide a working example, that would be _so_ helpful.)

I set the `limit` to `50`, I omit `ticker`, and I call the endpoint multiple times (after waiting the delay), but it doesn't seem to update with more records. 

Am I supposed to look for the ID of the last item in the array and then pass that as a `cursor` and then keep doing that until fewer than 50 results are returned?

How are the records sorted, and is there a way to pass a sort field and direction as a parameter?

Thank you so much!  :-D

**Comment by ZaneH** [comment]
> 
> Hi friends at Zabo,

🙋‍♂️

> 
> It wasn't obvious that "Optional ID of the resource to start from" meant the transaction ID, but that seems to be the case.
> 

Yes, this could be more clear. The Optional ID is the "cursor" in this case and the incoming transactions come after the cursor.

> In my attempts to fetch _all_ transactions for a given account ID, it's still not clear to me how to do it. (If you could provide a working example, that would be _so_ helpful.)
> 

<details>
<summary>open-source-soon.js</summary>
You won't need all of this to fetch all transactions, but I included it for context.
<br />
<br />

```javascript
// Fetch account details
async fetchAccount(userId, accountId) {
    const data = await this.getAccount(userId, accountId)

    data.transactions = []
    data.metadata = {}

    // Populate data.transactions
    let page
    do {
        // Get the next page of transactions if available, otherwise getTransactions
        page = await (page ? page.next() : this.getTransactions(userId, accountId))
        const newTxs = page.data || []

        // Push transactions
        data.transactions = _.uniqBy([...data.transactions, ...newTxs], 'id')

        // Set metadata
        data.metadata.delay = page.delay
        data.metadata.last_updated_at = page.last_updated_at || Date.now()
        data.metadata.next_update_at = page.delay && Date.now() + (page.delay * 1000)
        data.metadata.last_request_id = page.request_id || data.metadata.last_request_id
    } while (page.hasMore)

    // Fiat value is ready
    const hasFiatValues = _.some(data.transactions, tx =>
        _.some(tx.parts, p => !!p.fiat_value)
    )

    data.metadata.ready = !data.transactions.length || hasFiatValues

    return data
}
```
</details>

> I set the `limit` to `50`, I omit `ticker`, and I call the endpoint multiple times (after waiting the delay), but it doesn't seem to update with more records.
> 

Are you doing this from a server or client? If you're using the SDK on a server, but sure to include `userId` and `accountId` arguments to `transactions.getList({ ... })`.

> Am I supposed to look for the ID of the last item in the array and then pass that as a `cursor` and then keep doing that until fewer than 50 results are returned?
> 

Yes, when you reach the end of the list, `page.hasMore` (in the code above) will be false.

> Thank you so much! :-D

😁

**Comment by ryancwalsh** [comment]
Thank you so much for your quick response, @ZaneH !

I'm using the SDK on the server, not the frontend JS client.

And so I don't think `page.hasMore` and `page.next()` exist, right? I don't see them in the example JSON returned in the "Zabo JS Server" section of https://zabo.com/docs/?javascript--zabo-server#get-transaction-history (or in my own experience running it).

I see:

```
data: [{id: "39928a35-d3f4-54cc-a502-7b06080c5352", status: "completed", transaction_type: "deposit",…},…]
delay: 86
has_errors: false
last_updated_at: 1620162900899
request_id: "55285919-81c1-4a4c-8edc-934b2ae059d0"
```

I'm curious what you recommend for server-side.

And also do you know when the WebSocket approach will be available?

Thanks! :-D

**Comment by Hackdom** [comment]
Also...
> How are the records sorted, and is there a way to pass a sort field and direction as a parameter?
Transactions are sorted by timestamp in descending order, there's no way to change either the sort field nor direction at the moment.
> Do you know when that will be available?
Regarding websockets, not yet. There's been a lot of requests for things we are prioritizing, websockets has not come up directly, but we can add your input to make it a priority.
> I set the limit to 50, I omit ticker, and I call the endpoint multiple times (after waiting the delay), but it doesn't seem to update with more records.
Just to add to this. Are you using the sandbox in these requests? Or are these live server requests?

**Comment by Hackdom** [comment]
> And so I don't think page.hasMore and page.next() exist, right? I don't see them in the example JSON returned in the "Zabo JS Server" section of https://zabo.com/docs/?javascript--zabo-server#get-transaction-history (or in my own experience running it).

These are actual utils available from the JS SDK. They are not explicitly exposed in the JSON object.

**Comment by ryancwalsh** [comment]
Thank you both so much!

I think this may have worked!

```
/* eslint-disable import/prefer-default-export */
/* eslint-disable @typescript-eslint/no-var-requires */
import _uniqBy from 'lodash/uniqBy';
import { createResponse } from './zabo';
import { jsonify } from '../lib/utils';

const Zabo = require('zabo-sdk-js');

require('dotenv').config();

const env = process.env.ZABO_ENV;
const defaultUserId = process.env.ZABO_USER_ID;
const apiKey = process.env.ZABO_API_KEY;
console.log({ env, userId: defaultUserId, apiKey });

// eslint-disable-next-line max-lines-per-function
async function getTransactions({ zabo, userId, accountId, ticker = undefined, limit = 50, cursor = undefined }) {
  console.log('getTransactions', jsonify({ userId, accountId, ticker, limit, cursor }));
  const data = {
    metadata: {
      delay: null,
      last_updated_at: null,
      next_update_at: null,
      last_request_id: null,
    },
    transactions: [],
  };

  // Docs: https://zabo.com/docs/#get-transaction-history and https://github.com/zabo-api/zabo-sdk-js/issues/68

  let page;
  let pageNum = 1;
  do {
    // Get the next page of transactions if available, otherwise getTransactions
    // eslint-disable-next-line no-await-in-loop
    page = await (page
      ? page.next()
      : zabo.transactions.getList({
          userId,
          accountId,
          ticker,
          limit, // 2 to 50 https://zabo.com/docs/#pagination
          cursor, // Optional ID of the resource to start from https://zabo.com/docs/#pagination
        }));
    console.log('pageNum', pageNum, 'page', jsonify(page));
    const newTxs = page.data || [];

    // Push transactions
    data.transactions = _uniqBy([...data.transactions, ...newTxs], 'id');

    // Set metadata
    data.metadata.delay = page.delay;
    data.metadata.last_updated_at = page.last_updated_at || Date.now();
    data.metadata.next_update_at = page.delay && Date.now() + page.delay * 1000;
    data.metadata.last_request_id = page.request_id || data.metadata.last_request_id;
    pageNum += 1;
  } while (page.hasMore);

  console.log('acctTransactions', jsonify(data));
  return data.transactions;
}

export const handler = async (event, context) => {
  const userId = event.queryStringParameters.userId || defaultUserId;
  const { ticker, accountId } = event.queryStringParameters;
  return createResponse((zabo) => {
    return getTransactions({ zabo, userId, accountId, ticker });
  });
};
```
