### ISSUE TITLE
Create user returning Cannot read property 'users' of undefined

### ISSUE THREAD

**Issue by adobayua-rpay** [zabo-api/zabo-sdk-js#73]
`  zabo.connect().onConnection(async account => {

  .then(zabo => {
      console.log(account)
      zabo.users.create(account)
    }).catch(e => {
      console.log(e.message)
    })
    zabo.user.create(account).then(function(user) {
      console.log(user)
      /* user is the object outlined below */
    })
    .catch(function(error) {
      console.log(error)
      /* See errors section for more information */
    })

  }).onError(async error => {
    console.log('Failed')
    console.error('account connection error:', error.message)
  })`

**Comment by marcelodesouza** [comment]
Hi @adobayua-rpay 

Thanks for using Zabo SDK!

Is your app Frontend or Backend?
Creating users is possible only in Backend side.

After initializing the Zabo SDK, you should be able to create an user by following the docs:
https://zabo.com/docs/?javascript--zabo-server#create-a-user

The error "Cannot read property 'users' of undefined" means that your `zabo` instance is not available in the scope where you are trying to use it, and it is not actually an issue in the SDK.

Maybe I can help you better if you paste here more parts of your code.

Cheers!

**Comment by dreinke** [comment]
Closing this because it has been inactive for a few weeks.
Please reopen if you still encounter this issue with the latest stable version.
